//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aleApiTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedule
    {
        public int idSchedule { get; set; }
        public string SchDescription { get; set; }
        public string SchWeekSelect { get; set; }
        public System.TimeSpan SchTimeInit { get; set; }
        public System.TimeSpan SchTimeEnd { get; set; }
        public int idUsersCoath { get; set; }
        public int idLocation { get; set; }
        public bool IsActive { get; set; }
        public string NickName { get; set; }
    }
}
