//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aleApiTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int idUser { get; set; }
        public string userDNI { get; set; }
        public string userEmail { get; set; }
        public string userPhoneNumber { get; set; }
        public string userFirstname { get; set; }
        public string userLastname { get; set; }
        public string userUsername { get; set; }
        public string userPassword { get; set; }
        public string userAvatar { get; set; }
        public System.DateTime userDateCreate { get; set; }
        public System.DateTime userDateUpdate { get; set; }
        public int idRole { get; set; }
        public string userOldPassword { get; set; }
        public string Color { get; set; }
        public string NickName { get; set; }
    }
}
